---
title: "DATA621_Final"
author: "Calvin Wong"
date: "11/6/2019"
output: pdf_document
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(knitr)
library(pROC)
library(ROCit)
library(dplyr)
library(skimr)
```


```{r message=FALSE, warning=FALSE, include=FALSE}
peo <- read_csv("https://raw.githubusercontent.com/cwong79/DATA621/Calvin/Final%20Project/PEO1.csv")
```

```{r}
peo = subset(peo, select = -c(X1, `CANCEL DATE`, `LOCATION CANCEL DATE`, `WRAP-UP INDICATOR`))
```

```{r}
set.seed(305)
peo$HealthRating <- sample(1:5, replace = T)
peo$WCRating <- sample(1:5, replace = T)
peo$StrategyRating <- sample(1:5, replace = T)
peo$CostRating <- sample(1:5, replace = T)
peo$SupportRating <- sample(1:5, replace = T)
```

```{r}
peo %>%
  skim()
```


```{r}
peo$NAICSClassCode <- as.numeric(substr(peo$NAICS, start = 1, stop = 2))
```
```{r}
type <- c("Agriculture, Forestry, Fishing and Hunting", 
          "Mining", 
          "Utilities", 
          "Construction", 
          "Manufacturing", 
          "Wholesale Trade", 
          "Retail Trade",
          "Transportation and Warehousing", 
          "Information", 
          "Finance and Insurance", 
          "Real Estate Rental and Leasing", 
          "Professional, Scientific, and Technical Services", 
          "Management of Companies and Enterprises", 
          "Administrative and Support and Waste Management and Remediation Services", 
          "Educational Services", 
          "Health Care and Social Assistance", 
          "Arts, Entertainment, and Recreation", 
          "Accommodation and Food Services", 
          "Other Services (except Public Administration)", 
          "Public Administration")
naicsdata <- data.frame(type)
peo$NAICS_TYPE <- cut(peo$NAICSClassCode, c(1, 11, 21, 22, 23, 34, 42, 46, 50, 51, 52, 53, 54, 55, 57, 61, 63, 71, 73, 82, Inf), type)
```

```{r}
train <- peo[ which(peo$`NAMED INSURED`=='ADP TOTAL SOURCE INC'), ]
train <- select(train, -c(HealthRating, WCRating, StrategyRating, CostRating, SupportRating))
set.seed(306)
train$HealthRating <- sample(3:5, replace = T)
train$WCRating <- sample(2:4, replace = T)
train$StrategyRating <- sample(1:3, replace = T)
train$CostRating <- sample(3:5, replace = T)
train$SupportRating <- sample(2:4, replace = T)
```

```{r}
test <- peo[ -which(peo$`NAMED INSURED`=='ADP TOTAL SOURCE INC'), ]
```

```{r}
test %>% group_by(test$`NAMED INSURED`) %>% summarize(count=n())
```

```{r}

```

